"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Color_1 = require("./Color");
Color_1.default.parseRelative("color(from red a98-rgb r g b)");
// Color.parseRelative("color(from red a98-rgb r g b / alpha)");
// Color.parseRelative("color(from red xyz-d50 x y z)");
// Color.parseRelative("color(from red xyz-d50 x y z / alpha)");
// Color.parseRelative("hsl(from red calc(h + 100) s l)");
// Color.parseRelative("hsl(from red h s l / alpha)");
// Color.parseRelative("hwb(from red 66 w b)");
// Color.parseRelative("hwb(from red h w b / alpha)");
// Color.parseRelative("lab(from red l a b)");
// Color.parseRelative("lab(from red alpha a b / calc(l - 5))");
// Color.parseRelative("lch(from red l c h)");
// Color.parseRelative("lch(from red l c calc(h + (100 - 50)) / alpha)");
// Color.parseRelative("oklab(from red l a b)");
// Color.parseRelative("oklab(from red l a b / alpha)");
// Color.parseRelative("oklch(from red l c h)");
// Color.parseRelative("oklch(from red l c h / alpha)");
// Color.parseRelative("rgb(from red r g b)");
// Color.parseRelative("rgb(from red r g b / alpha)");
